name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Create ZIP file
      run: zip -r function.zip .

    - name: Upload ZIP file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: lambda-function
        path: function.zip

    - name: Deploy to AWS Lambda
      env:
        AWS_REGION: 'us-east-2'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        FUNCTION_NAME: 'ynab-currency'
      run: |
        aws lambda update-function-code \
          --function-name $FUNCTION_NAME \
          --zip-file fileb://function.zip \
          --region $AWS_REGION


